### ISSUE TITLE
how to start menuconfig on zephyr-ide GUI

### ISSUE THREAD

**Issue by IOT4566** [mylonics/zephyr-ide#10]
![001](https://github.com/mylonics/zephyr-ide/assets/169084509/13b6edbc-2d42-485f-bc02-6beb703fc459)

I can run 'west build -t menuconfig' cmd in powershell, but i cann't find entry button on zephyr-ide gui

**Comment by rijesha** [comment]
Im not sure where the best place for this to go in the GUI would be. Im thinking maybe there should be another panel showing the configuration. 
Or do you think this should just be in the command pallete as opposed to a GUI button?

**Comment by IOT4566** [comment]
> Im not sure where the best place for this to go in the GUI would be. Im thinking maybe there should be another panel showing the configuration. Or do you think this should just be in the command pallete as opposed to a GUI button?

I thinking the kconfig and devicetree be another panel showing the configuration best.

**Comment by IOT4566** [comment]
I mean the menuconfig and devicetree config  be another panel showing the configuration best. we can refer nrf connect extend.

**Comment by black-ghost-off** [comment]
west build -t menuconfig -b %current selected board%

add that to 
![image](https://github.com/mylonics/zephyr-ide/assets/70693212/114af3a8-8063-4348-91ac-10c44cb2b896)

**Comment by rijesha** [comment]
Added in 1.0.23 in the active build panel
