### ISSUE TITLE
Presenting two boards as one

### ISSUE THREAD

**Issue by black-ghost-off** [mylonics/zephyr-ide#11]
The teensy boards have two versions 4.0 and 4.1, 
When selecting the Project > add build board, we select build as teensy4, but there should be two versions of teensy40 and teensy41, but only "teensy4" is available

https://docs.zephyrproject.org/latest/boards/pjrc/teensy4/doc/index.html

**Comment by rijesha** [comment]
Could you describe your problem further? It seems to work for me.
![image](https://github.com/mylonics/zephyr-ide/assets/7819200/b5f1a2b6-6ee6-4a96-9a1e-ae84f0561535)

![image](https://github.com/mylonics/zephyr-ide/assets/7819200/ba85dc7d-fe71-4482-b4a8-dbe87be87594)

**Comment by black-ghost-off** [comment]
![image](https://github.com/mylonics/zephyr-ide/assets/70693212/a5b0d08c-15a5-42cd-ab7e-371f05c4b273)

**Comment by rijesha** [comment]
Can you send a screenshot of the contents of the teensy board directory. So {root_board_dir}/boards/arm/teensy4

**Comment by black-ghost-off** [comment]
![image](https://github.com/mylonics/zephyr-ide/assets/70693212/42b153c5-a162-4c91-a7cf-03013fce6bb7)

**Comment by black-ghost-off** [comment]
![image](https://github.com/mylonics/zephyr-ide/assets/70693212/b552a816-8f50-4662-b7e1-5f5b23f7ee89)
![image](https://github.com/mylonics/zephyr-ide/assets/70693212/13780a0d-da7d-4203-bbdc-32b7c0c825fe)
i was try rewrite all "teensy4" to teensy40 board
![image](https://github.com/mylonics/zephyr-ide/assets/70693212/70fb1369-6f7a-480c-99e2-45ccec6ba178)
but something still want to use "teensy4" for build

**Comment by rijesha** [comment]
if you look in your settings.json you can manually change the teensy4 to teensy40. 

I'm not sure why you are only seeing teensy 4.
When creating a build can you show me what your "Pick a Board directory" looks like and what you button you are pressing?

**Comment by rijesha** [comment]
actually I have found the problem. I will get a fix going.

**Comment by rijesha** [comment]
A fix has been made. V1.0.13 should be available in the next 5 minutes.

**Comment by black-ghost-off** [comment]
Solved, thanks)
