### ISSUE TITLE
Custom flash loader for "teensy"

### ISSUE THREAD

**Issue by black-ghost-off** [mylonics/zephyr-ide#12]
https://github.com/mylonics/zephyr-ide/issues/11 The build is going well. However, the problem now is that I can't add a runner for flash teensy (there is a custom bootloader without swd/jtag and it is necessary only through their utility ( https://www.pjrc.com/teensy/loader_cli.html )

**Comment by black-ghost-off** [comment]
I know. However, zephyr natively supports teensy_cli (you need to specify the path of the utility), I mean it should work in our case out of the box)

Offtop: I have already tested xiao seeed ble(nrf52840), nucleo h563zi, nrf52840 devkit, everything works fine with the IDE
Now in progress testing xiao seeed ESP32s3, esp32s3 devkit n8r8

**Comment by rijesha** [comment]
could you give me the west command you would run to load the code.

**Comment by black-ghost-off** [comment]
Just 
> west flash 
![image](https://github.com/mylonics/zephyr-ide/assets/70693212/e5355bea-561e-4b3f-a42d-cc39b05e856d)

**Comment by black-ghost-off** [comment]
path "teensy_loader_cli.exe" in added to PATH

**Comment by rijesha** [comment]
I pushed an update (1.0.15) that allows the default west flash to be run for this board. You will have to pass the runner arguments when you setup the runner. ("-H -r teensy")

**Comment by black-ghost-off** [comment]
![image](https://github.com/mylonics/zephyr-ide/assets/70693212/3ae8ddc3-57cd-4826-8f53-3bf71f6b4815)
![image](https://github.com/mylonics/zephyr-ide/assets/70693212/cd8d0d53-2444-43e0-8478-44f91001109e)

If built with https://docs.zephyrproject.org/latest/develop/getting_started/index.html
But the project that is created by the IDE does not lend itself to 
>west flash --build-dir “.\build\teensy40\”

**Comment by rijesha** [comment]
What is the build command that you use?

 The error is correct and the teensy folder does not have a board.cmake file I think that is why there is no zephyr_runners_yaml

**Comment by rijesha** [comment]
What version of zephyr did you use for the build that works and what version are you using with zephyr-ide?

**Comment by rijesha** [comment]
Ok. I think the problem is that you are using the v3.6.0 release of zephyr. That version doesn't have support for the teensy cli flasher.

Change the revision in application/west.yml file from v3.6.0 to main and then run a west update.

**Comment by rijesha** [comment]
You will also need to remake the build configurations, because main has the board directories reorganized.

**Comment by IOT4566** [comment]
Zephyr ide retrieves the supported runners for this board by traversing board.cmake file in the board directory, but unfortunately, teensy4 does not include board.cmake, while other boards do

**Comment by IOT4566** [comment]
Zephyrproject requirements the`board.cmake` file must have

**Comment by black-ghost-off** [comment]
I change 3.6.0 to main, and that fix problem well. For feature add option for select version of zephyr?

**Comment by rijesha** [comment]
The west init function should now have that ability.
