### ISSUE TITLE
Are there plans to add these two features? Devicetree Visual Editor UI&&Kconfig GUI

### ISSUE THREAD

**Issue by hongshui3000** [mylonics/zephyr-ide#13]
I hope the extension can have the same features as nrf connect for vscode: 
Wish list: 
Devicetree Visual Editor UI 
nrf Kconfig GUI

This extension can generate some commands to nRF Kconfig and nRF Kconfig, allowing them to open the configuration device and kconfig

**Comment by rijesha** [comment]
There is currently no plans to add those features. The visual editor would be complicated.
There is a [device tree extension](https://marketplace.visualstudio.com/items?itemName=trond-snekvik.devicetree) that may work. I haven't tried it though.
A Kconfig GUI is more manageable, but currently no plans for that either.
With a KConfig GUI I am not sure what configuration options to include and what not to.
