### ISSUE TITLE
Bug: Two versions of one board

### ISSUE THREAD

**Issue by black-ghost-off** [mylonics/zephyr-ide#14]
![image](https://github.com/mylonics/zephyr-ide/assets/70693212/e364f5cc-3766-4204-8711-9e0af1736bbd)
![image](https://github.com/mylonics/zephyr-ide/assets/70693212/a25d5b1b-3f81-4c60-9522-76920de3e658)

When selecting the ESP32s3 devkit board (in my case esp32s3 devkit c(n8r8), I see two choices, esp32s3_devkitc_appcpu and esp32s3_devkitc_procpu, although only esp32s3_devkitc is in the list of available boards

**Comment by black-ghost-off** [comment]
Versions:
west: v1.2.0
zephyr: main
SDK: 0.16.2

(Off-topic, add a feature somewhere so that you can get all versions of all packages)

**Comment by rijesha** [comment]
Where is the 2nd screenshot from? It sounds like that board has two cpu cores on it and you need to select what core you are building for.
I would imagine one of them is the bluetooth core.

**Comment by rijesha** [comment]
> Versions: west: v1.2.0 zephyr: main SDK: 0.16.2
> 
> (Off-topic, add a feature somewhere so that you can get all versions of all packages)

What do you mean all versions of all packages?

**Comment by black-ghost-off** [comment]
2nd screenshot it`s if there is an error that such a board does not exist, ``west build`` displays a list of all supported boards

**Comment by black-ghost-off** [comment]
> What do you mean all versions of all packages?

One button for copy version of sdk, west, zephyr, arm packages, esp pacakges, etc...

**Comment by rijesha** [comment]
This issue is closed. Select the correct processor for the board you are building and you should be good.

**Comment by black-ghost-off** [comment]
This is an issue that there is no correct configuration in the build configuration selection

**Comment by black-ghost-off** [comment]
@rijesha reopen issue

**Comment by rijesha** [comment]
I dont think I understand the issue. What are you expecting in the build configuration selection.

**Comment by black-ghost-off** [comment]
The list when selecting the build configuration contains those boards that do not exist, and the one that is needed is not there. You only need esp32s3_devkitc WITHOUT appcpu, procpu

**Comment by rijesha** [comment]
Also if you are having build issues with that board, this may be relevant.
https://github.com/zephyrproject-rtos/zephyr/issues/72639

**Comment by black-ghost-off** [comment]
> Also if you are having build issues with that board, this may be relevant.
> https://github.com/zephyrproject-rtos/zephyr/issues/72639

![Screenshot_2024-05-15-07-30-47-131_com.github.android.jpg](https://github.com/mylonics/zephyr-ide/assets/70693212/d620746e-2823-4572-ac18-f12cad4f9d5a)

**Comment by black-ghost-off** [comment]
Doesn't meter, main always on 0 core boot(only if you wasn't touch idf menuconfig)

Two cores controlled by rtos, that cores doesn't have two different firmwares

We need select JUST "esp32s3_devkitc" for build firmware 

I don't know where from appcpu and *second name", it's not in list of available board(esp32s3_devkitc_appcpu and esp32_divkitc_otherboard)

My flow
Create new project
Select build configuration 
Select BOARD esp32s3_devkitc
BUT configuration menu give me list without "ZEPHYR SUPPORTED BOARD", it's give me "(esp32s3_devkitc_appcpu and esp32_divkitc_otherboard)"

THERE BUG, WHAT WE NEED ESP32S3_DEVKITC(WITHOUT ANYTHING ELSE)

**Comment by black-ghost-off** [comment]
Bug in list of your zephyr IDE, build configuration 
List where you select which one board you want to use

**Comment by rijesha** [comment]
Please post the west build command that you would use if you weren't using zephyr ide.

**Comment by black-ghost-off** [comment]
https://github.com/mylonics/zephyr-ide/assets/70693212/47fbd7a2-b33e-4d1f-8fd6-e794d32bb6f9

**Comment by black-ghost-off** [comment]
https://docs.zephyrproject.org/latest/boards/espressif/esp32s3_devkitc/doc/index.html

**Comment by black-ghost-off** [comment]
I suspect that the bug may be in the SDK/West/Zephyr itself

**Comment by rijesha** [comment]
There is a bug with the zephyr ide app. Hopefully I will be able to have a look at it today.

**Comment by black-ghost-off** [comment]
One observation. 
>west build -besp32s3_devkitc 
is also not possible, it is necessary as I dropped in the link earlier

**Comment by rijesha** [comment]
So there have been a lot of changes recently with the way the boards are being handled.

I think the zephyr ide works correctly if you are using v3.6.0. 
I made some changes that work with main, but that will break v3.6.0 and lower.

I would recommend using v3.6.0 for the time being. If using v3.6.0 then you can use esp32s3_devkitc as you pointed out earlier. The zephyr documentation and zephyr main have all changed to using esp32s3_devkitc/esp32/appcpu.

If you would really like to use main, you can manually edit the board for the project in settings.json.

**Comment by rijesha** [comment]
I got my changes to work for both the new and older version of zephyr. It is in v1.20.0

**Comment by black-ghost-off** [comment]
LGMT, It works
