### ISSUE TITLE
click west init button, then select nrf connect config then error exit

### ISSUE THREAD

**Issue by IOT4566** [mylonics/zephyr-ide#15]
![006](https://github.com/mylonics/zephyr-ide/assets/169084509/51426dfd-4d4a-43e1-a387-ec7e6c0b7537)
![005](https://github.com/mylonics/zephyr-ide/assets/169084509/89bbd1e9-afe6-488e-acce-4e0dadd94a89)

1.0.18, click west init button, then select nrf connect config then error exit

**Comment by rijesha** [comment]
That is a bug in the west template. I have issued a fix.

**Comment by IOT4566** [comment]
it is ok now, but I suggest removing --narrow, otherwise sometimes errors may occur, and I have already encountered them, then i try remove --narrow and it is well

**Comment by rijesha** [comment]
ok I will remove narrow and it will be included with the next fix
