### ISSUE TITLE
please add custom west.yml item on west init

### ISSUE THREAD

**Issue by IOT4566** [mylonics/zephyr-ide#16]
I think it would be better to handle the west init : first, let the user choose the version number, such as 3.6 or 2.7.6 (LTS) or other version, next there should be an option to list all the supported architectures for that version in the western yml step, and provide a checkbox for users to select multiple. Finally, generate the western yml file based on the user's selection and initialize it
for example, user select nordic, espressif and telink then the west.yml will include flowing module
.- hal_noridic
.- hal_espressif
.- hal_telink

**Comment by rijesha** [comment]
What should the full list of items look like? And in your opinion should other modules be included?

**Comment by IOT4566** [comment]
> What should the full list of items look like? And in your opinion should other modules be included(i.e libmetal, lvgl)?

![001](https://github.com/mylonics/zephyr-ide/assets/169084509/1e7c9373-08af-4c80-9eef-a99613875507)
The the full list of items is the zephyrproject supported all hal_xxx l

**Comment by rijesha** [comment]
Added in 1.0.23
