### ISSUE TITLE
Method to add extra west build and CMake arguments

### ISSUE THREAD

**Issue by rpiper** [mylonics/zephyr-ide#19]
Would it be possible to add some new `"buildConfigs"` options that allow passing optional extra arguments both to `west build` and extra CMake arguments off the end, i.e. `west build ... --  -DEXTRA_ARG=1` ?

I understand these are not commonly used, so they could probably be available to edit in the config.json only, and not the UI.

The use case for the extra argument to `west build` would be to add the `--sysbuild` argument if using [sysbuild to build a multi-image build](https://docs.zephyrproject.org/latest/build/sysbuild/index.html), which is often used when building with the MCUboot bootloader.

There are many possible extra CMake arguments, but a common one that might be used for a release build would be to set
`-DNDEBUG=1`

as in

`west build ... -- -DNDEBUG=1`

I'm happy to help test any possible solution that allows adding these extra arguments to the buildConfig.

**Comment by rijesha** [comment]
Yes. This should be doable. Ill put it on the todo list.

**Comment by hongshui3000** [comment]
It would be more convenient if CMakePresets.json could be supported like nrf connect for vscode.
![image](https://github.com/mylonics/zephyr-ide/assets/25566498/9aa698aa-87e9-4c60-976b-a701306ecdea)
