### ISSUE TITLE
Please add a menuconfig button for each board. 

### ISSUE THREAD

**Issue by IOT4566** [mylonics/zephyr-ide#26]
![001](https://github.com/mylonics/zephyr-ide/assets/169084509/044cdb22-38ee-4367-b145-af211c6f964d)

Although the active project already includes the menuconfig button, it is obvious that adding the menuconfig button to each board in the project also be convenient

**Comment by rijesha** [comment]
There is a prerelease version of the app that will be available v1.0.28. This version adds the button where you indicated.

Please note that the new version no longer uses the debugOptimization variable and that by using the new version you will not be able to downgrade. (So save a copy of your projects in settings.json (or zephyr-ide.json)

**Comment by IOT4566** [comment]
thinks！
