### ISSUE TITLE
Missing telink(hal_telink)

### ISSUE THREAD

**Issue by IOT4566** [mylonics/zephyr-ide#27]
![002](https://github.com/mylonics/zephyr-ide/assets/169084509/9b11df0b-7830-4fc9-9c18-b112c457a98e)

In west init setup, not found telink(hal_telink) item can be select. I suggest that all options should be obtained by traversing the zephyr/west.yml file in that zephyr version, so as not to miss anything

**Comment by rijesha** [comment]
implemented in 1.0.24
