### ISSUE TITLE
The pop-up information during building does not match the actual situation

### ISSUE THREAD

**Issue by IOT4566** [mylonics/zephyr-ide#3]
![001](https://github.com/mylonics/zephyr-ide/assets/169084509/58f8050e-b2be-4125-b94d-a1dcdcc275a3)
![002](https://github.com/mylonics/zephyr-ide/assets/169084509/b8b7f7b3-72e6-4b42-83ad-01985c328223)
![003](https://github.com/mylonics/zephyr-ide/assets/169084509/13ba6f3d-6118-4f65-9b25-46bbb5f759af)

The pop-up information during compilation does not match the actual situation.
I add 3 build for blink,. pic1, I am building "nrf52840dk_nrf52840" ,but pop-up show "build esp32c3_devkitm", pic2, i am building "esp32c3_devkitm" ,but pop-up show "build tlsr9518adk80d", pic3, i am building "tlsr9518adk80d" ,but pop-up show "build esp32c3_devkitm"
I found a rule that pop ups display information from the previous compilation, not the current compilation

**Comment by rijesha** [comment]
Thank you again for the issue. Ill have a look.

**Comment by rijesha** [comment]
I have pushed an update 1.0.9. It should be fixed there.

**Comment by IOT4566** [comment]
> I have pushed an update 1.0.9. It should be fixed there.

yes, 1.0.9 is ok, thanks!
