### ISSUE TITLE
Add Project action buttons to primary bar

### ISSUE THREAD

**Issue by beriberikix** [mylonics/zephyr-ide#36]
It would be convenient to have action buttons for the active project displayed on the primary bar at the bottom. Once I've set up my project and build, I'm usually focused on the file explorer. I've found myself needing to switch back and forth between the extension UI to run a build (or use the command palette.)

Here's an example from PlatformIO
![image](https://github.com/mylonics/zephyr-ide/assets/178376/20625a40-326f-40a0-a68f-115677ff8229)

**Comment by rijesha** [comment]
What all actions do you think should be available there?

**Comment by rijesha** [comment]
There is a prerelease version of the app that will be available v1.0.28. That includes the GUI changes to add some buttons in the status menu.

Please note that the new version no longer uses the debugOptimization variable and that by using the new version you will not be able to downgrade. (So save a copy of your projects in settings.json (or zephyr-ide.json)

**Comment by rijesha** [comment]
We can reopen this issue if there are any missing buttons.
