### ISSUE TITLE
Project management issues delete, add

### ISSUE THREAD

**Issue by zafersn** [mylonics/zephyr-ide#44]
Hi,

I have two different projects in the same workspace, but havea problem with the second project crpto. I cant delete it from the project list, cant add a build config. while having no problem with the board-test project,

Both of them are in the same workspace.

![image](https://github.com/mylonics/zephyr-ide/assets/13236364/e9b41e2c-8069-47f0-a846-36368152c619)

![Screenshot 2024-06-23 152917](https://github.com/mylonics/zephyr-ide/assets/13236364/e3f601d0-1aef-4690-ab84-7450a33c84d1)

this error output: 

![image](https://github.com/mylonics/zephyr-ide/assets/13236364/3d9cc099-513c-45bb-969c-d5fa211d890b)

**Comment by rijesha** [comment]
Also did you make the project with the current version or a previous version of the extension?

**Comment by zafersn** [comment]
Hi @rijesha 

> Are you able to build the projects just fine? Are you able to share a repo of your workspace?
board-hw-test project is built fine. No problem. But when  I add another project, it wont be built, even though its in the same workspace the board-hw-test prj

> Those error outputs are not directly relevant to removing a project, but they shouldn't happen.
Well, actually, removing the project issue was because of me, I blocked the zephyr notf. so when I tried to delete it, it asked for permission through the notif. So thats why I missed them, and though I cant delete them,. 




> Also did you make the project with the current version or a previous version of the extension?

I am using v1.0.35 of it. is it uptodate?

**Comment by rijesha** [comment]
Yea v1.0.35 is up to date. Could you reinitialize the workspace and see if it fixes it. Is the project visible in your settings.json file?

**Comment by rijesha** [comment]
I just pushed a new version of v1.0.36.  Install the new version and run `Zephyr IDE: Debug Internal Shell` and post the contents here. You can do this by opening the command pallet and running the command. Then in the output window, select zephyr-ide and you will see the contents.

Ctrl-p -> Zephyr IDE: Debug Internal Shell

**Comment by rijesha** [comment]
Closing this as stale. Let me know if the issue persists
