### ISSUE TITLE
Add ability to configure global install location

### ISSUE THREAD

**Issue by mstrow** [mylonics/zephyr-ide#46]
Add the ability to configure the global install location.

Some options of how to set this:

- Set using extension config option
- Set using environment variable. PlatformIO does this using the PLATFORMIO_CORE_DIR variable. For example, Zephyr IDE could use ZEPHYR_IDE_GLOBAL_DIR

**Comment by rijesha** [comment]
This is implemented in v1.1.2 (pre-release stream).
Please try it out and let me know if you run into any issues.
Any folder can be selected as the west root during setup. In the settings.json you can specify zephyr-ide.tools_directory for a custom directory for the sdk to be downloaded and installed into.
