### ISSUE TITLE
Missing pyelftools module 

### ISSUE THREAD

**Issue by LLC09** [mylonics/zephyr-ide#47]
Hi, on macOS 14.5
when building an example, the cmake issues an error regarding missing packet pyelftools.
I fix this by running /opt/homebrew/Cellar/west/1.2.0_2/libexec/bin/python -m pip install pyelftools.
To be noticed: During the init phase of the Zephyr IDE extension, I choose "Using Local Zephyr Install" in the EXTENSION SETUP menu.

**Comment by rijesha** [comment]
pyelftools is in zephyr\scripts\requirements-base.txt. So it should be installed during the zephyr ide west update task. Did you run west update and did it succeed?

**Comment by rijesha** [comment]
Closing as stale
