### ISSUE TITLE
Extension doesn't show in sidebar

### ISSUE THREAD

**Issue by ronsegal** [mylonics/zephyr-ide#48]
On Ubuntu  22.04.4 LTS with all required zephyr getting started extensions installed and version verified including python3 venv, Zephyr IDE vscode extension 1.0.36 appears to install without error but does not appear in the task sidebar (or in the list of sidebar extensions). Other IDE extensions do appear, platformio etc. Have tried uninstalling re-installing restarting vscode etc but can't get the Zephyr IDE extension to appear.  Suggestions appreciated.

**Comment by rijesha** [comment]
Could you try an earlier version of the extension like 1.0.35 and see if that works.
If you right click on the activity bar is zephyr ide an option there?

**Comment by ronsegal** [comment]
Thanks for getting back.  I've tried both of two versions before the latest, still with no Zephyr IDE available in the left hand activity bar at all, hidden or otherwise.  The task bar at the bottom does contain Zephyr IDE functional icons, also the command pallet shows Zephyr IDE commands.

**Comment by djr-spectrummfg** [comment]
I had this problem, I was able to fix it by deleting the entire extensions folder (`%USERPROFILE%\.vscode\extensions` or `~/.vscode/extensions`) and installing just the zephyr IDE plugin. Probably this is overkill though.

**Comment by rijesha** [comment]
I'm not sure what is causing this problem, but I will have a look into it further when I have some time.

**Comment by ronsegal** [comment]
Thanks djr and Rijesh.  On your suggestion djr I removed all extensions and started again (perhaps a good idea anyway) with a blank sheet.  Zephyr IDE now shows in the sidebar.  Suggest that's more of a workaround than solving the underlying problem, some kind of clash with another extension.  Will get back if I manage to discover which one(s), although that might of course depend on installation order.

**Comment by ronsegal** [comment]
Further. By the look the clash is with the Python Environment Manager extension plus the Python extension being mutually exclusive with Zephyr IDE on the activity bar.  Sorry no time to investigate further, though obviously a significant issue with those Python extensions being key ones.

**Comment by gBonvenuto** [comment]
I believe this should be noted in the Know Issues on the README until we have a fix

**Comment by rijesha** [comment]
@gBonvenuto feel free to make a PR.

**Comment by rijesha** [comment]
@ronsegal Why do you think it is related to python extensions or do you think it is just that your local python extension was causing a conflict?

**Comment by rijesha** [comment]
If anyone runs into the issue again could you post any error messages from the developer console?
F1 > Developer: Toggle Developer Tools > Console

**Comment by rijesha** [comment]
I found the issue. It was specifically with the python environment manager extension. Thanks @ronsegal your findings really helped. 
This is all that was needed to change. 0b3f8af329d6a33d6d462530e995e302472836bf

**Comment by rijesha** [comment]
Also bug report added to the python environment manager extension. https://github.com/DonJayamanne/vscode-python-manager/issues/94

**Comment by ronsegal** [comment]
Well done, very much appreciate the fix.
