### ISSUE TITLE
Unable to open. dts file for non arm architecture

### ISSUE THREAD

**Issue by IOT4566** [mylonics/zephyr-ide#5]
![001](https://github.com/mylonics/zephyr-ide/assets/169084509/9e793f08-a058-4710-ae54-c334433c320b)
![002](https://github.com/mylonics/zephyr-ide/assets/169084509/5de9302c-2cec-4701-b568-0be29f81d675)
 
Unable to open. dtc file for non arm architecture。pic1:when i click "Board nrf52840dk_nrf52840" item, then auto to open nrf52840dk_nrf52840.dts, but when i when i click "Board tlsr9518adk80d" item, tlsr9518adk80d.dts file cann't be open. 
Later, I found that it was because the function parameter in pic2  was fixed to ‘arm’, changing this parameter to the arch type of the board can solve this problem。

**Comment by rijesha** [comment]
Thanks for the issue. I will get a fix going.

**Comment by rijesha** [comment]
I fixed this in version 1.0.10. Should be available in a few minutes.

**Comment by IOT4566** [comment]
> I fixed this in version 1.0.10. Should be available in a few minutes.

https://github.com/mylonics/zephyr-ide/assets/169084509/8c87240f-0540-4701-8d0b-b53adec742b8

cann't open non arm board dts files still

**Comment by rijesha** [comment]
It works for me when I do the same board.
Can you see if the log shows anything: Ctrl-Shift-p -> Show Logs -> Extension Host
Can you also send the settings.json file?

**Comment by IOT4566** [comment]
> It works for me when I do the same board. Can you see if the log shows anything: Ctrl-Shift-p -> Show Logs -> Extension Host Can you also send the settings.json file?

![log1](https://github.com/mylonics/zephyr-ide/assets/169084509/d8380fab-ef8e-4127-87a6-0d020ebf76f2)

**Comment by IOT4566** [comment]
> It works for me when I do the same board. Can you see if the log shows anything: Ctrl-Shift-p -> Show Logs -> Extension Host Can you also send the settings.json file?

![002](https://github.com/mylonics/zephyr-ide/assets/169084509/660fb4f4-103c-4d4f-939d-2108483d7b55)

arch of esp32c3 is not arm

**Comment by rijesha** [comment]
Can you also send the settings.json file?

**Comment by rijesha** [comment]
When I did this with a fresh build it works fine.

**Comment by IOT4566** [comment]
> When I did this with a fresh build it works fine.

[settings.json](https://github.com/mylonics/zephyr-ide/files/15239022/settings.json)

**Comment by rijesha** [comment]
So in the settings file the relBoardSubDir is "relBoardSubDir": "arm\\esp32c3_devkitm".

Did you manually change the setting file? Any build defined before v1.0.10 would need to have the setting files manually changed. 
Could you also make a new build and post what the relBoardSubDir is?

**Comment by IOT4566** [comment]
> So in the settings file the relBoardSubDir is "relBoardSubDir": "arm\esp32c3_devkitm".
> 
> Did you manually change the setting file? Any build defined before v1.0.10 would need to have the setting files manually changed. Could you also make a new build and post what the relBoardSubDir is?

no, the settings file is generate auto

**Comment by IOT4566** [comment]
The settings file is generate auto before 1.0.10, it not match 1.0.10

**Comment by rijesha** [comment]
Ok. So any builds made before v1.0.9 (that are not arm) you will need to manually set the relBoardSubDir.

**Comment by rijesha** [comment]
By build I mean build configuration, not the action of performing a "build" or "build pristine".

**Comment by rijesha** [comment]
This should fix the problem with the other issue as well.

**Comment by IOT4566** [comment]
> This should fix the problem with the other issue as well.这也应该解决另一个问题的问题。

ok

**Comment by IOT4566** [comment]
OK,this issuse is fixed
