### ISSUE TITLE
'Build and Debug' should not start debugger if build fails

### ISSUE THREAD

**Issue by djr-spectrummfg** [mylonics/zephyr-ide#50]
Currently, if I press the 'Build and Debug' button and my build fails, the debugger is started anyway using an old binary. This is very confusing and should not happen.

**Comment by rijesha** [comment]
Noted. Will have a look at into it.

**Comment by rijesha** [comment]
Hi could you try the latest prerelease version of the app and see if the issue is resolved. >V1.0.37. There are other gui related changes on the prerelease version as well.

**Comment by VitekST** [comment]
@rijesha Works for me.
