### ISSUE TITLE
zephyr-ide.get-gdb-path uses backslashes

### ISSUE THREAD

**Issue by gBonvenuto** [mylonics/zephyr-ide#53]
`${command:zephyr-ide.get-gdb-path}"` uses backslashes which is incompatible in unix systems.

Current solution: use `"${command:zephyr-ide.get-toolchain-path}/arm-zephyr-eabi/bin/arm-zephyr-eabi-gdb"` instead

**Comment by rijesha** [comment]
Thanks for the issue. Ill have a look into changing it when I have some time.

**Comment by rijesha** [comment]
This is fixed in v1.0.41. Will reopen if you are still experiencing issues.
