### ISSUE TITLE
Initialize west.yml in root of the workspace instead of application/west.yml

### ISSUE THREAD

**Issue by andre-stefanov** [mylonics/zephyr-ide#65]
Currently the west.yml is being created in `application/west.yml` this contradicts the zepyhr example application setup and also leads to the "workspace initialization from repo" bug mentioned in https://github.com/mylonics/zephyr-ide/issues/63#issuecomment-2381602140

solution: workspace initialization should create the west.yml file directly in the root of the workspace

unfortunatelly doing this manually in the repo also leads to a new issue, where west init is being executed into RepoName.git instead of the repository root :(

**Comment by rijesha** [comment]
The IDE is designed for a multiproject workspace that shares the same west.yml. Unfortunately west does not support that well. In whatever directory the west.yml file, the parent directory of that file will contain the .west directory. 

The initialize from git repository will initialize a project like this https://github.com/zephyrproject-rtos/example-application. If you want to use a workspace maintained by the zephyr ide you should do a git clone and get the repo on your computer and then open that directory with vscode.

**Comment by andre-stefanov** [comment]
alright thank you :) in that case i'll close the issue
