### ISSUE TITLE
Build with --sysbuild for mcuboot failed 

### ISSUE THREAD

**Issue by rokobertcm** [mylonics/zephyr-ide#66]
I'm using ZephyrIDE 1.3.3 on MacOS 14.7 with MacBook Pro M3.

When I try to build app for mcuboot with --sysbuild argument, I get error and failed.
If I build project alone it is Ok.
If I manually run command in bash or zsh terminal it is also Ok. Then I could build without -p. Only pristine is problem.
Manual command from terminal is:
>west build -b ECO00189 /Users/robert.konc/Soft/zpIDE3/B300 -p --build-dir >/Users/robert.konc/Soft/zpIDE3/B300/build/bootECO00189 --sysbuild -- -DBOARD_ROOT='/Users/robert.konc/Soft/zpIDE3'   ->DEXTRA_CONF_FILE='/Users/robert.konc/Soft/zpIDE3/B300/prj_ble.conf;/Users/robert.konc/Soft/zpIDE3/B300/prj_release.conf;

Here is log from terminal.

> Executing task: west build -b ECO00189 /Users/robert.konc/Soft/zpIDE3/B300 -p --build-dir /Users/robert.konc/Soft/zpIDE3/B300/build/bootECO00189 --sysbuild -- -DBOARD_ROOT='/Users/robert.konc/Soft/zpIDE3'   -DEXTRA_CONF_FILE='/Users/robert.konc/Soft/zpIDE3/B300/prj_ble.conf;/Users/robert.konc/Soft/zpIDE3/B300/prj_release.conf;'  
> 
> -- west build: making build dir /Users/robert.konc/Soft/zpIDE3/B300/build/bootECO00189 pristine
> -- west build: generating a build system
> Loading Zephyr module(s) (Zephyr base): sysbuild_default
> -- Found Python3: /Users/robert.konc/Soft/zpIDE3/.venv/bin/python (found suitable version "3.12.5", minimum required is "3.8") found components: Interpreter
> -- Cache files will be written to: /Users/robert.konc/Library/Caches/zephyr
> -- Found west (found suitable version "1.2.0", minimum required is "0.14.0")
> -- Board: ECO00189, qualifiers: nrf52840
> Parsing /Users/robert.konc/Soft/zpIDE3/external/zephyr/share/sysbuild/Kconfig
> Loaded configuration '/Users/robert.konc/Soft/zpIDE3/B300/build/bootECO00189/_sysbuild/empty.conf'
> Merged configuration '/Users/robert.konc/Soft/zpIDE3/B300/sysbuild.conf'
> Configuration saved to '/Users/robert.konc/Soft/zpIDE3/B300/build/bootECO00189/zephyr/.config'
> Kconfig header saved to '/Users/robert.konc/Soft/zpIDE3/B300/build/bootECO00189/_sysbuild/autoconf.h'
> -- 
>    *****************************
>    * Running CMake for mcuboot *
>    *****************************
> 
> Loading Zephyr default modules (Zephyr base).
> -- Application: /Users/robert.konc/Soft/zpIDE3/external/bootloader/mcuboot/boot/zephyr
> -- CMake version: 3.30.2
> -- Found Python3: /opt/homebrew/bin/python (found suitable version "3.12.5", minimum required is "3.8") found components: Interpreter
> -- Cache files will be written to: /Users/robert.konc/Library/Caches/zephyr
> -- Zephyr version: 3.7.99 (/Users/robert.konc/Soft/zpIDE3/external/zephyr)
> CMake Error at /Users/robert.konc/Soft/zpIDE3/external/zephyr/cmake/modules/boards.cmake:198 (message):
>   Error finding board: ECO00189
> 
>   Error message: Traceback (most recent call last):
> 
>     File "/Users/robert.konc/Soft/zpIDE3/external/zephyr/scripts/list_boards.py", line 11, in <module>
>       import pykwalify.core
> 
>   ModuleNotFoundError: No module named 'pykwalify'
> 
> Call Stack (most recent call first):
>   /Users/robert.konc/Soft/zpIDE3/external/zephyr/cmake/modules/zephyr_default.cmake:133 (include)
>   /Users/robert.konc/Soft/zpIDE3/external/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)
>   /Users/robert.konc/Soft/zpIDE3/external/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)
>   CMakeLists.txt:12 (find_package)
> 
> 
> -- Configuring incomplete, errors occurred!
> CMake Error at cmake/modules/sysbuild_extensions.cmake:486 (message):
>   CMake configure failed for Zephyr project: mcuboot
> 
>   Location:
>   /Users/robert.konc/Soft/zpIDE3/external/bootloader/mcuboot/boot/zephyr
> Call Stack (most recent call first):
>   cmake/modules/sysbuild_images.cmake:20 (ExternalZephyrProject_Cmake)
>   cmake/modules/sysbuild_default.cmake:20 (include)
>   /Users/robert.konc/Soft/zpIDE3/external/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:75 (include)
>   /Users/robert.konc/Soft/zpIDE3/external/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)
>   /Users/robert.konc/Soft/zpIDE3/external/zephyr/share/sysbuild-package/cmake/SysbuildConfig.cmake:8 (include)
>   template/CMakeLists.txt:10 (find_package)
> 
> 
> -- Configuring incomplete, errors occurred!
> FATAL ERROR: command exited with status 1: /opt/homebrew/bin/cmake -DWEST_PYTHON=/Users/robert.konc/Soft/zpIDE3/.venv/bin/python -B/Users/robert.konc/Soft/zpIDE3/B300/build/bootECO00189 -GNinja -DBOARD=ECO00189 -DBOARD_ROOT=/Users/robert.konc/Soft/zpIDE3 '-DEXTRA_CONF_FILE=/Users/robert.konc/Soft/zpIDE3/B300/prj_ble.conf;/Users/robert.konc/Soft/zpIDE3/B300/prj_release.conf;' -S/Users/robert.konc/Soft/zpIDE3/external/zephyr/share/sysbuild -DAPP_DIR:PATH=/Users/robert.konc/Soft/zpIDE3/B300
> 
>  *  The terminal process "/bin/bash '-l', '-c', 'west build -b ECO00189 /Users/robert.konc/Soft/zpIDE3/B300 -p --build-dir /Users/robert.konc/Soft/zpIDE3/B300/build/bootECO00189 --sysbuild -- -DBOARD_ROOT='/Users/robert.konc/Soft/zpIDE3'   -DEXTRA_CONF_FILE='/Users/robert.konc/Soft/zpIDE3/B300/prj_ble.conf;/Users/robert.konc/Soft/zpIDE3/B300/prj_release.conf;' '" terminated with exit code: 1. 
>  *  Terminal will be reused by tasks, press any key to close it. 
>

**Comment by rijesha** [comment]
Does the problem occur on zephyr-ide 1.3.2 (recreate the project in that version and see if it persists)? Is this a custom board?

**Comment by rokobertcm** [comment]
I'm tested in 1.3.0 version. Same problem.
Yes it is custom board.
But if I build only application ( no --sysbuild) it works.

**Comment by rijesha** [comment]
You can try running west update and trying again. 
You can also try manually installing the python requirements.
https://github.com/zephyrproject-rtos/zephyr/blob/main/scripts/requirements.txt
Can you also share you settings.json file?

**Comment by rokobertcm** [comment]
West update. Same result update git but not requirements.
Manualy install requirements.
Run build ok.
Run build with --sysbuild same error.
In attachment is settings.json file.
[settings.json](https://github.com/user-attachments/files/17223197/settings.json)

**Comment by rijesha** [comment]
I'm not sure what the problem is. It could be related to using mac os or it could be related to the project configuration.
Easiest way to debug is for you to share your full workspace.

**Comment by rokobertcm** [comment]
I'm testing Zephyr IDE extension under Ubuntu 24.4 LTS (aarch64) virtual machine. Virtual host app is VmWare Fusion. Host machine is MacBook Pro M3.
Version 1.3.3 work as it should. I'm testing all things which make problems under MacOS and here all works as it should.
I'm also copy workspace folder from MacOs to Ubuntu and build. In my opinion it is nothing wrong with project configuration.

Regards.

**Comment by rokobertcm** [comment]
I will close this issue. It is same bug as in #55.
