### ISSUE TITLE
hello word and bluetooth template is not list

### ISSUE THREAD

**Issue by IOT4566** [mylonics/zephyr-ide#7]
![007](https://github.com/mylonics/zephyr-ide/assets/169084509/86e6ba17-af0e-4f99-b725-f7bc8a2d37ff)

the samples template is too less, hello word and bluetooth template is not list, "samples" instead of "samples/basic"?

**Comment by rijesha** [comment]
I agree. I was thinking of the best way of doing this. Maybe a multiple step input where a user could select choose between the main directories, then choose subdirectories within.

**Comment by hongshui3000** [comment]
For displaying information such as list names, [zephyr-ide] can use the sample.yaml file under the directory, similar to what [nrf-connect] does.

**Comment by rijesha** [comment]
Add with #20
