### ISSUE TITLE
Add new boards or board variants

### ISSUE THREAD

**Issue by Rohan-RSA** [mylonics/zephyr-ide#78]
Hello,

This is my first issue so excuse me if I do not have the proper format.
I would like to add the following 2 boards to the boards directory: 
1.) nucleo_u031r8 (very new)
2.) nucleo_f303ze (my own port from the nucleo_f303ze)

But I cannot build when I copy and paste these boards into the directory: .....\STM32_Workspace\external\zephyr\boards\st
(Where all the other ST boards are) I have tried `west update`. After I added any new boards to this folder then I cannot even build for the boards that are there by default. 

The error in the screenshot is: 
`ERROR: Malformed "build" section in file: C:/Projects/Gitlab/STM32_Workspace/external/zephyr/boards/st/nucleo_u031r8/board.yml
<SchemaError: error code 2: Schema validation failed:
 Key 'full_name' was not defined. Path: '/board'.: Path: '/'>`

Please see below screenshots for reference.  Your guidance would be much appreciated.

![Screenshot 2024-11-14 152339](https://github.com/user-attachments/assets/f7f16a21-0dcd-49d5-a42f-5805b8a6c665)

![Screenshot 2024-11-14 153202](https://github.com/user-attachments/assets/804fbf8d-c3a4-4f50-aa57-ac937b55e41c)

**Comment by rijesha** [comment]
Hello.
This seems more like a zephyr rtos question than something specific to the VSCode extension.

I think the problem is that you are duplicating your board name. You need to modify board.yml and add a unique name for the board. You currently have nucleo_XX.yaml open and not board.yml.

**Comment by Rohan-RSA** [comment]
Hello @rijesha , thank you for the reply. I downloaded the entire `nucleo_u031r8` folder from github and pasted it in the boards directory. Thus I thought that it should all be correct. Please see the `board.yaml` screenshot and let me know what you think please. 
![Screenshot 2024-11-14 200727](https://github.com/user-attachments/assets/7ec42c80-0d05-4d9c-a926-d785473089fb)

**Comment by Rohan-RSA** [comment]
Hi @rijesha , I saw that the zephyr ide has this output:
`ERROR: Malformed "build" section in file: C:/Projects/Gitlab/STM32_Workspace/external/zephyr/boards/st/nucleo_u031r8/board.yml
<SchemaError: error code 2: Schema validation failed:
 - Key 'full_name' was not defined. Path: '/board'.: Path: '/'>
ERROR: SoC 'stm32u031xx' is not found, please ensure that the SoC exists and that soc-root containing 'stm32u031xx' has been correctly defined.`

This dht22 sample project was originally for an nRF DK but I just changed `sample.yaml` to the following:
`    platform_allow: stm32u031xx
    integration_platforms:
      - stm32u031xx`

Does this output help to possibly identify my issue?

![Screenshot 2024-11-14 202054](https://github.com/user-attachments/assets/3b034e7a-2e2d-4cfc-b98c-6ad3f1c6e120)

**Comment by rijesha** [comment]
Again this isn't really a zephyr ide issue.
If you are trying to add a new board that already exists in the zephyr repo then you should clone that version of zephyr in its entirety to make sure all dependencies are met. In your west.yml or west init you should select main as the version of zephyr instead of v3.7/v3.6 or whatever you have right now. If you already have main selected then do a west update to get the new board.

**Comment by Rohan-RSA** [comment]
Ok, thank you for your time. I am still quite an amateur hence my questions. 

Best regards
