### ISSUE TITLE
When the system did not install cmake first, but the zephyr-ide did not pop-up error info，and some error exit in building project phase.

### ISSUE THREAD

**Issue by IOT4566** [mylonics/zephyr-ide#8]
When the system did not install cmake first, but the zephyr-ide did not pop-up error info，and some error exit in building project phase. Suggest check cmake in the checkIfToolsAvailable API same as check python and git

**Comment by rijesha** [comment]
Thanks for the issue. I will implement that check

**Comment by IOT4566** [comment]
> Thanks for the issue. I will implement that check

Devicetree Compiler should check also?

**Comment by rijesha** [comment]
I added both of these checks. Thanks for the issue.
