### ISSUE TITLE
Add runner selector like project/build selector to status bar

### ISSUE THREAD

**Issue by rijesha** [mylonics/zephyr-ide#80]

**Comment by glenn-andrews** [comment]
Is there a way to add additional runners to the list?

I'm using openocd on a disco_l475_iot1 board, and the only option is `default`. I'd like to be able to add `openocd` as an option so I can select it, even if I then have to play with launch.json to set up the configuration file, etc.

Right now I'm selecting default, then going into zephyr-ide.json and modifying `runnerConfigs` by hand.
