### ISSUE TITLE
Selecting Kconfig requires .conf file extension

### ISSUE THREAD

**Issue by StephenKercherPP** [mylonics/zephyr-ide#92]
When trying to link a KConfig in the extension, the Browse/Open window has a filter for files with (.conf) file extensions.
Many KConfigs that i have seen are ONLY named `KConfig` - No File Extension.
![image](https://github.com/user-attachments/assets/c900efff-88c1-4cc7-a787-4f9282b953f7)

Are there specific KConfig files that you are expecting?

**Comment by rijesha** [comment]
I have no idea. I assumed they all had a .conf extension. I pushed a fix to remove the filter in 1.5.4.

**Comment by StephenKercherPP** [comment]
I look forward to it!

p.s. May want to keep your changelog up-to-date.  Makes the Zephyr IDE Extension seem more professional.  ;)

**Comment by rijesha** [comment]
Closing this issue as implemented. We can reopen if there are issues.
